### ISSUE TITLE
ZEND_ECHO

### ISSUE THREAD

**Issue by Yousha** [jpauli/jpauli.github.io#22]
In this article http://jpauli.github.io/2015/02/05/zend-vm-executor.html#performance-tips you said using `echo $foo, $bar` is faster(better performance) than using echo `$foo . $bar`... right?
But my simple Benchmark says different thing:

**Code:**
```
<?php
$foo = 'foo';
$bar = 'bar';

function timer()
{
   static $_Microtime;
   if ($_Microtime != 0) return (microtime(1) - $_Microtime);
   $_Microtime = microtime(1);
}

timer();

for ($i = 0; $i < 1000; $i ++)
{
   echo $foo.$bar;
}

echo timer(); 
?>
```
**Result:**
0.16900992393494
0.17300987243652
0.17901015281677
0.18001103401184
0.18101096153259

**Code:**
```
<?php
$foo = 'foo';
$bar = 'bar';

function timer()
{
   static $_Microtime;
   if ($_Microtime != 0) return (microtime(1) - $_Microtime);
   $_Microtime = microtime(1);
}

timer();

for ($i = 0; $i < 1000; $i ++)
{
   echo $foo,$bar;
}

echo timer(); 
?>
```
**Result:**
0.33201909065247
0.33201903065247
0.34201913065147
0.34401109065247
0.35201909161243

**Conclusion:**
Using `echo $foo . $bar;` is FASTER than `echo $foo, $bar;`

**Comment by jpauli** [comment]
PHP version ?

**Comment by Yousha** [comment]
**PHP 5.6**

**Comment by jpauli** [comment]
Yeah, that is probably due to machine error.

Testing with such a small payload (6 bytes) is not representative.
Should be more representative with a higher load (several hundreds or thousands of bytes)

**Comment by Yousha** [comment]
Machine error? then can you show me a better benchmark with its result?

_I did it with PHP 5.6 64-bit in 64-bit OS(Windows/Slackware Linux), x64 hardware and 4GB RAM_

**Comment by jpauli** [comment]
What I mean is that you need to increment the payload.  Try with many strings (hundreds), of many bytes (thousands) ; that should be ok
